"""
IND_core.py -- independent re-implementation (2026-10-09) of the basic objects used to check the facet list of the
(2,2,d) local polytope L.  Written from scratch; imports NOTHING from the earlier scripts of this folder.

Conventions (deliberately different from facet_lib.py, which drops outcome d-1):
  * deterministic points lam = (a0, a1, b0, b1), index ((a0 d + a1) d + b0) d + b1;
  * affine coordinates X of the no-signalling space: outcome 0 is DROPPED:
        [pA(a|x) : x = 0,1; a = 1..d-1] + [pB(b|y) : y = 0,1; b = 1..d-1] + [p(ab|xy) : x, y; a, b = 1..d-1];
  * a facet is stored as its SLACK TENSOR s[lam] = h0 - h.X(lam) >= 0 (primitive integer vector over the d^4
    deterministic points), which is coordinate-free; (h0, h) in MY coordinates is re-derived exactly from s;
  * G = (S_d)^4 x| D_4: outcome permutations of the four measurements and the 8 setting/party symmetries
    (generated by a0<->a1, b0<->b1, (a0,a1)<->(b0,b1)), acting on slack tensors by permuting axes and indices.
Exact linear algebra: python-flint (fmpz_mat / fmpq_mat).  The matcher (explicit relabelling) is numba-compiled;
it only PRUNES with hash values and decides by exact integer comparison of all d^4 entries.
"""
import itertools
import math
import numpy as np
import numba as nb
import flint


# ----------------------------------------------------------------------------- scenario
class Scen:
    def __init__(self, d):
        self.d = d
        self.lams = np.array(list(itertools.product(range(d), repeat=4)), dtype=np.int64)
        self.nl = d ** 4
        self.dim = 4 * d * (d - 1)
        self.X = np.array([self.coords_det(l) for l in self.lams], dtype=np.int64)
        self.perms = np.array(list(itertools.permutations(range(d))), dtype=np.int64)
        self.sigmas = d4_axis_perms()
        self.order = 8 * math.factorial(d) ** 4

    def coords_det(self, lam):
        d = self.d
        a = (lam[0], lam[1]); b = (lam[2], lam[3])
        v = []
        for x in range(2):
            for aa in range(1, d):
                v.append(int(a[x] == aa))
        for y in range(2):
            for bb in range(1, d):
                v.append(int(b[y] == bb))
        for x in range(2):
            for y in range(2):
                for aa in range(1, d):
                    for bb in range(1, d):
                        v.append(int(a[x] == aa and b[y] == bb))
        return v

    def coords_behaviour(self, P):
        """P[x][y][a][b] (exact entries: ints/Fractions/flint.fmpq) -> my coordinates (list, same type)."""
        d = self.d
        v = []
        for x in range(2):
            for aa in range(1, d):
                v.append(sum(P[x][0][aa][b] for b in range(d)))
        for y in range(2):
            for bb in range(1, d):
                v.append(sum(P[0][y][a][bb] for a in range(d)))
        for x in range(2):
            for y in range(2):
                for aa in range(1, d):
                    for bb in range(1, d):
                        v.append(P[x][y][aa][bb])
        return v

    def orig_cg_det(self, lam):
        """facet_lib.py's documented convention (outcome d-1 dropped) -- used ONLY to convert the saved facet
        vectors of adj_d4_small_final.pkl into slack tensors."""
        d = self.d
        a = (lam[0], lam[1]); b = (lam[2], lam[3])
        v = []
        for x in range(2):
            for aa in range(d - 1):
                v.append(int(a[x] == aa))
        for y in range(2):
            for bb in range(d - 1):
                v.append(int(b[y] == bb))
        for x in range(2):
            for y in range(2):
                for aa in range(d - 1):
                    for bb in range(d - 1):
                        v.append(int(a[x] == aa and b[y] == bb))
        return v

    def slack_from_saved(self, f):
        """saved facet vector f = (h0, h) (orig. CG convention) -> slack tensor (python ints, exact)."""
        h0, h = int(f[0]), [int(t) for t in f[1:]]
        s = []
        for lam in self.lams:
            c = self.orig_cg_det(lam)
            s.append(h0 - sum(hi * ci for hi, ci in zip(h, c)))
        return np.array(s, dtype=np.int64)


def d4_axis_perms():
    """closure of the generators a0<->a1, b0<->b1, party swap, as axis permutations of (a0,a1,b0,b1)."""
    gens = [(1, 0, 2, 3), (0, 1, 3, 2), (2, 3, 0, 1)]
    out = {(0, 1, 2, 3)}
    frontier = [(0, 1, 2, 3)]
    while frontier:
        nxt = []
        for s in frontier:
            for g in gens:
                c = tuple(s[g[i]] for i in range(4))
                if c not in out:
                    out.add(c)
                    nxt.append(c)
        frontier = nxt
    out = sorted(out)
    assert len(out) == 8
    return np.array(out, dtype=np.int64)


# ----------------------------------------------------------------------------- exact linear algebra
def rank_exact(rows):
    if len(rows) == 0:
        return 0
    return flint.fmpz_mat([[int(x) for x in r] for r in rows]).rank()


def affine_rank_exact(P):
    P = [[int(x) for x in r] for r in P]
    if len(P) <= 1:
        return 0
    b = P[0]
    return rank_exact([[x - y for x, y in zip(r, b)] for r in P[1:]])


def primitive(v):
    g = 0
    for x in v:
        g = math.gcd(g, int(x))
    return [int(x) // g for x in v] if g > 1 else [int(x) for x in v]


def functional_from_slack(sc, s):
    """(h0, h) in MY coordinates with h0 - h.X(lam) = s[lam] for all lam (exact, verified on all points)."""
    n = sc.dim
    # affine basis of the deterministic points: greedy, exact
    basis = []
    rows = []
    for i in range(sc.nl):
        trial = rows + [[1] + [int(x) for x in sc.X[i]]]
        if rank_exact(trial) == len(trial):
            rows = trial
            basis.append(i)
            if len(basis) == n + 1:
                break
    assert len(basis) == n + 1
    # unknowns w = (h0, h): h0 - h.X = s  ->  [1, -X] w = s
    A = flint.fmpq_mat([[1] + [-int(x) for x in sc.X[i]] for i in basis])
    b = flint.fmpq_mat([[int(s[i])] for i in basis])
    w = A.solve(b)
    wl = [w[i, 0] for i in range(n + 1)]
    den = 1
    for q in wl:
        den = den * int(q.q) // math.gcd(den, int(q.q))
    wi = [int(q * den) for q in wl]
    # verify on ALL points: h0 - h.X(lam) = s[lam] * den
    h0, h = wi[0], np.array(wi[1:], dtype=object)
    for i in range(sc.nl):
        assert h0 - int(np.dot(h, sc.X[i].astype(object))) == int(s[i]) * den
    return den, wi                      # den * s = h0 - h.X


def is_facet_slack(sc, s):
    s = np.asarray(s)
    if s.min() < 0:
        return False
    T = np.nonzero(s == 0)[0]
    return affine_rank_exact(sc.X[T].tolist()) == sc.dim - 1


# ----------------------------------------------------------------------------- matcher (numba)
@nb.njit(cache=True)
def _pair_hashes(A, W, d):
    HA = np.zeros((d, d), np.uint64)
    HB = np.zeros((d, d), np.uint64)
    for a0 in range(d):
        for a1 in range(d):
            for b0 in range(d):
                for b1 in range(d):
                    w = W[A[a0, a1, b0, b1]]
                    HA[a0, a1] += w
                    HB[b0, b1] += w
    return HA, HB


@nb.njit(cache=True)
def _match_fixed_axes(S, T, perms, W, d, find_all):
    """outcome permutations (p0,p1,p2,p3) (rows of perms) with T[p0[a0],p1[a1],p2[b0],p3[b1]] == S[a0,a1,b0,b1]
    for all entries.  Returns (count, i0, i1, i2, i3) of the first match (count = number of matches if
    find_all)."""
    HAS, HBS = _pair_hashes(S, W, d)
    HAT, HBT = _pair_hashes(T, W, d)
    P = perms.shape[0]
    vA = np.empty((P * P, 2), np.int64)
    nA = 0
    for i0 in range(P):
        for i1 in range(P):
            ok = True
            for o0 in range(d):
                for o1 in range(d):
                    if HAT[perms[i0, o0], perms[i1, o1]] != HAS[o0, o1]:
                        ok = False
                        break
                if not ok:
                    break
            if ok:
                vA[nA, 0] = i0
                vA[nA, 1] = i1
                nA += 1
    vB = np.empty((P * P, 2), np.int64)
    nB = 0
    for i2 in range(P):
        for i3 in range(P):
            ok = True
            for o2 in range(d):
                for o3 in range(d):
                    if HBT[perms[i2, o2], perms[i3, o3]] != HBS[o2, o3]:
                        ok = False
                        break
                if not ok:
                    break
            if ok:
                vB[nB, 0] = i2
                vB[nB, 1] = i3
                nB += 1
    count = 0
    f0 = -1; f1 = -1; f2 = -1; f3 = -1
    for ka in range(nA):
        p0 = perms[vA[ka, 0]]
        p1 = perms[vA[ka, 1]]
        for kb in range(nB):
            p2 = perms[vB[kb, 0]]
            p3 = perms[vB[kb, 1]]
            ok = True
            for a0 in range(d):
                for a1 in range(d):
                    for b0 in range(d):
                        for b1 in range(d):
                            if T[p0[a0], p1[a1], p2[b0], p3[b1]] != S[a0, a1, b0, b1]:
                                ok = False
                                break
                        if not ok:
                            break
                    if not ok:
                        break
                if not ok:
                    break
            if ok:
                if count == 0:
                    f0 = vA[ka, 0]; f1 = vA[ka, 1]; f2 = vB[kb, 0]; f3 = vB[kb, 1]
                count += 1
                if not find_all:
                    return count, f0, f1, f2, f3
    return count, f0, f1, f2, f3


def transpose_axes(A, ax):
    return np.ascontiguousarray(np.transpose(A, ax))


@nb.njit(cache=True)
def _invariant(A, W, d):
    """G-invariant hash: (value histogram hash, sorted multiset of the 4d one-dimensional slice hashes)."""
    h1 = np.uint64(0)
    sl = np.zeros(4 * d, np.uint64)
    for a0 in range(d):
        for a1 in range(d):
            for b0 in range(d):
                for b1 in range(d):
                    w = W[A[a0, a1, b0, b1]]
                    h1 += w
                    sl[0 * d + a0] += w * np.uint64(3) + np.uint64(1)
                    sl[1 * d + a1] += w * np.uint64(3) + np.uint64(1)
                    sl[2 * d + b0] += w * np.uint64(3) + np.uint64(1)
                    sl[3 * d + b1] += w * np.uint64(3) + np.uint64(1)
    s = np.sort(sl)
    h2 = np.uint64(1469598103934665603)
    for t in range(4 * d):
        h2 = (h2 ^ s[t]) * np.uint64(1099511628211)
    return h1, h2


class Matcher:
    """exact G-equivalence of slack tensors with explicit relabellings."""

    def __init__(self, sc, vmax=4096, seed=20261009):
        self.sc = sc
        rng = np.random.default_rng(seed)
        self.W = rng.integers(1, 2 ** 62, size=vmax + 1, dtype=np.int64).astype(np.uint64)
        self.vmax = vmax

    def tensor(self, s):
        d = self.sc.d
        s = np.asarray(s, dtype=np.int64)
        assert s.min() >= 0 and s.max() <= self.vmax
        return np.ascontiguousarray(s.reshape(d, d, d, d))

    def invariant(self, s):
        h1, h2 = _invariant(self.tensor(s), self.W, self.sc.d)
        return (int(h1), int(h2))

    def find(self, s_target, s_cand):
        """explicit g = (sigma, p0..p3) with  cand_sigma[p0[a0],p1[a1],p2[b0],p3[b1]] == target[a0,a1,b0,b1],
        cand_sigma = np.transpose(cand, sigma); verified again in numpy.  None if no such g exists (the
        search is exhaustive: hashes only prune pairs that cannot match)."""
        d = self.sc.d
        S = self.tensor(s_target)
        C = self.tensor(s_cand)
        for si, sig in enumerate(self.sc.sigmas):
            T = transpose_axes(C, tuple(int(x) for x in sig))
            cnt, i0, i1, i2, i3 = _match_fixed_axes(S, T, self.sc.perms, self.W, d, False)
            if cnt:
                p = self.sc.perms
                chk = T[np.ix_(p[i0], p[i1], p[i2], p[i3])]
                assert np.array_equal(chk, S), "matcher verification failed"
                return (si, int(i0), int(i1), int(i2), int(i3))
        return None

    def stabiliser_order(self, s):
        d = self.sc.d
        S = self.tensor(s)
        tot = 0
        for sig in self.sc.sigmas:
            T = transpose_axes(S, tuple(int(x) for x in sig))
            cnt, *_ = _match_fixed_axes(S, T, self.sc.perms, self.W, d, True)
            tot += int(cnt)
        return tot
