"""
IND_ns.py -- independent check (2026-10-09) of hypothesis (ii) of Theorem V for L(2,2,4): every vertex of the
no-signalling polytope NS(2,2,4) outside L violates a listed facet.  Own code only (IND_core, IND_dd).

  (B)  all vertices of NS by the independent exact DD (IND_dd) of the cone {(t, X) : c_i t + A_i X >= 0} in my
       coordinates (outcome 0 dropped); each output ray has t > 0 and tight rows of rank 48 (checked by IND_dd).
  (O)  the G-orbits of the canonical deterministic point and of the canonical generalised PR boxes PR_k (k = 2..4,
       PR_k[x][y][a][b] = 1/k iff a, b < k and b - a = xy mod k) are generated by breadth-first search over
       generators of G (setting swaps, party swap, outcome transpositions); every orbit element is checked to be
       a DD vertex and the orbit sizes add up to the number of DD vertices  =>  vert(NS) = union of the 4 orbits.
  (B') independent of (B): all NS-edges at the 4 canonical vertices (extreme rays of the tangent cones, IND_dd;
       exact ratio test); every neighbour lies in one of the 4 orbits.  The vertex-edge graph of a polytope is
       connected and G acts on NS, so again vert(NS) = union of the 4 orbits.
  (C)  for k = 2, 3, 4: the minimum over the whole PR_k orbit and over the 33 listed non-positivity class
       representatives of the exact affine slack; a negative value exhibits a listed facet violated by a relabelled
       PR_k, hence (G-invariance of the list) a listed facet violated by PR_k itself.
usage: python IND_ns.py [--threads k]
"""
import sys
import time
import json
import itertools
from fractions import Fraction
import numpy as np
from IND_core import Scen, functional_from_slack, rank_exact
from IND_expand import load_reps
import IND_dd

D = 4


def log(*a):
    print(*a, flush=True)


def positivity_forms(sc):
    """rows (c, A) with p(ab|xy) = c + A.X for my coordinates; verified on all deterministic points."""
    d = sc.d
    idxA = {}
    k = 0
    for x in range(2):
        for a in range(1, d):
            idxA[('A', x, a)] = k; k += 1
    for y in range(2):
        for b in range(1, d):
            idxA[('B', y, b)] = k; k += 1
    for x in range(2):
        for y in range(2):
            for a in range(1, d):
                for b in range(1, d):
                    idxA[('AB', x, y, a, b)] = k; k += 1
    keys, rows = [], []
    for x in range(2):
        for y in range(2):
            for a in range(d):
                for b in range(d):
                    v = [0] * (sc.dim + 1)
                    if a >= 1 and b >= 1:
                        v[1 + idxA[('AB', x, y, a, b)]] = 1
                    elif a >= 1:
                        v[1 + idxA[('A', x, a)]] = 1
                        for bb in range(1, d):
                            v[1 + idxA[('AB', x, y, a, bb)]] -= 1
                    elif b >= 1:
                        v[1 + idxA[('B', y, b)]] = 1
                        for aa in range(1, d):
                            v[1 + idxA[('AB', x, y, aa, b)]] -= 1
                    else:
                        v[0] = 1
                        for aa in range(1, d):
                            v[1 + idxA[('A', x, aa)]] -= 1
                        for bb in range(1, d):
                            v[1 + idxA[('B', y, bb)]] -= 1
                        for aa in range(1, d):
                            for bb in range(1, d):
                                v[1 + idxA[('AB', x, y, aa, bb)]] += 1
                    keys.append((x, y, a, b))
                    rows.append(v)
    C = np.array(rows, dtype=np.int64)
    for li, lam in enumerate(sc.lams):
        vals = C[:, 0] + C[:, 1:] @ sc.X[li]
        for i, (x, y, a, b) in enumerate(keys):
            assert vals[i] == int(lam[x] == a and lam[2 + y] == b)
    return keys, C


# ----------------------------------------------------------------------------- behaviours as integer tensors
def canon_det(d):
    P = np.zeros((2, 2, d, d), np.int64)
    P[:, :, 0, 0] = 1
    return P, 1


def canon_pr(d, k):
    P = np.zeros((2, 2, d, d), np.int64)
    for x in range(2):
        for y in range(2):
            for a in range(k):
                P[x, y, a, (a + x * y) % k] = 1
    return P, k                    # behaviour = P / k


def generators(d):
    gens = [lambda P: P[::-1, :, :, :].copy(),                       # Alice setting swap
            lambda P: P[:, ::-1, :, :].copy(),                       # Bob setting swap
            lambda P: np.ascontiguousarray(np.transpose(P, (1, 0, 3, 2)))]   # party swap
    for x in range(2):
        for o in range(d - 1):
            perm = np.arange(d); perm[o], perm[o + 1] = o + 1, o

            def ga(P, x=x, perm=perm):
                Q = P.copy(); Q[x] = P[x][:, perm, :]; return Q
            gens.append(ga)
    for y in range(2):
        for o in range(d - 1):
            perm = np.arange(d); perm[o], perm[o + 1] = o + 1, o

            def gb(P, y=y, perm=perm):
                Q = P.copy(); Q[:, y] = P[:, y][:, :, perm]; return Q
            gens.append(gb)
    return gens


def orbit(P0, gens):
    seen = {P0.tobytes(): P0}
    frontier = [P0]
    while frontier:
        nxt = []
        for P in frontier:
            for g in gens:
                Q = g(P)
                kb = Q.tobytes()
                if kb not in seen:
                    seen[kb] = Q
                    nxt.append(Q)
        frontier = nxt
    return list(seen.values())


def key12(P, den):
    """integer key 12 P / den (None if not integral)."""
    Q = P * (12 // den) if 12 % den == 0 else None
    return None if Q is None else Q.astype(np.int64).tobytes()


def coords_int(sc, P):
    """my coordinates of the integer tensor P (behaviour P/den): integer vector (times den)."""
    return np.array(sc.coords_behaviour(P.tolist()), dtype=np.int64)


def main():
    nthreads = 2
    if "--threads" in sys.argv:
        nthreads = int(sys.argv[sys.argv.index("--threads") + 1])
    T0 = time.time()
    sc = Scen(D)
    d = D
    keys, C = positivity_forms(sc)
    log(f"=== IND_ns d = {d}: 64 positivity forms in my coordinates (verified on all 256 deterministic points)")
    res = {}
    # ---------------------------------------------------------------- (O) orbits
    gens = generators(d)
    orbs = {}
    t0 = time.time()
    P, den = canon_det(d)
    orbs["deterministic"] = (orbit(P, gens), den)
    for k in range(2, d + 1):
        P, den = canon_pr(d, k)
        orbs[f"PR_{k}"] = (orbit(P, gens), den)
    sizes = {nm: len(o) for nm, (o, _) in orbs.items()}
    tot = sum(sizes.values())
    log(f"(O) orbit sizes under G (BFS over generators): {sizes}; total {tot}  [{time.time() - t0:.0f}s]")
    res["orbit_sizes"] = sizes
    orbit_keys = {}
    for nm, (o, den) in orbs.items():
        for P in o:
            orbit_keys[key12(P, den)] = nm
    assert len(orbit_keys) == tot, "orbits overlap"
    # every canonical point is a vertex of NS (tight forms of rank 48) and lies in NS
    for nm, (o, den) in orbs.items():
        P = o[0]
        X = coords_int(sc, P)
        vals = C[:, 0] * den + C[:, 1:] @ X                 # = den * p(ab|xy)
        flat = [int(P[x, y, a, b]) for (x, y, a, b) in keys]
        assert list(vals) == flat
        T = np.nonzero(vals == 0)[0]
        assert rank_exact(C[T, 1:].tolist()) == 48, nm
    log("    canonical points: behaviours reproduced by the positivity forms, all are vertices (tight rank 48)")
    # ---------------------------------------------------------------- (B) DD of NS
    t0 = time.time()
    R, Z, info = IND_dd.extreme_rays(C, seed=3, nthreads=nthreads, verbose=True, label="NS")
    nv = len(R)
    assert (R[:, 0] > 0).all(), "a ray with t <= 0: NS unbounded?"
    found = {}
    unrec = 0
    for r in range(nv):
        t = int(R[r, 0])
        vals = C[:, 0] * t + C[:, 1:] @ R[r, 1:]             # = t * p
        if ((12 * vals) % t != 0).any():
            unrec += 1
            continue
        Pk = np.zeros((2, 2, d, d), np.int64)
        for i, (x, y, a, b) in enumerate(keys):
            Pk[x, y, a, b] = 12 * int(vals[i]) // t
        nm = orbit_keys.get(Pk.tobytes())
        if nm is None:
            unrec += 1
        else:
            found[nm] = found.get(nm, 0) + 1
    log(f"(B) DD of NS: {nv} vertices (each checked: t > 0, feasible, tight rank 48), DD peak {info['peak']}, "
        f"max entry {info['maxentry']}; by orbit {found}; not in the 4 orbits: {unrec}  [{time.time() - t0:.0f}s]")
    okB = (unrec == 0) and (nv == tot) and found == sizes
    log(f"    vert(NS) = deterministic u PR_2 u PR_3 u PR_4 orbits: {okB}")
    res["B"] = dict(vertices=nv, by_orbit=found, unrecognised=unrec, ok=okB, dd=info)
    # ---------------------------------------------------------------- (B') edges at the canonical vertices
    t0 = time.time()
    okBp = True
    res["Bp"] = {}
    for nm, (o, den) in orbs.items():
        P = o[0]
        X = coords_int(sc, P)
        vals = C[:, 0] * den + C[:, 1:] @ X                 # den * p
        T = np.nonzero(vals == 0)[0]
        Rt, Zt, inf2 = IND_dd.extreme_rays(C[T, 1:], seed=5, nthreads=nthreads, verbose=False, label=nm)
        types = {}
        for r in Rt:
            Ar = C[:, 1:] @ r
            best = None
            for i in np.nonzero(Ar < 0)[0]:
                tt = Fraction(int(vals[i]), den * int(-Ar[i]))
                if best is None or tt < best:
                    best = tt
            assert best is not None and best > 0
            # neighbour behaviour: p_i(w) = vals_i/den + best * Ar_i
            wv = [Fraction(int(vals[i]), den) + best * int(Ar[i]) for i in range(len(keys))]
            assert min(wv) >= 0
            ok12 = all((12 * q).denominator == 1 for q in wv)
            if not ok12:
                types["UNRECOGNISED"] = types.get("UNRECOGNISED", 0) + 1
                continue
            Pk = np.zeros((2, 2, d, d), np.int64)
            for i, (x, y, a, b) in enumerate(keys):
                Pk[x, y, a, b] = int(12 * wv[i])
            tn = orbit_keys.get(Pk.tobytes(), "UNRECOGNISED")
            types[tn] = types.get(tn, 0) + 1
        okBp &= ("UNRECOGNISED" not in types)
        log(f"(B') {nm}: {len(T)} tight forms, {len(Rt)} NS-edges, neighbour types {types}")
        res["Bp"][nm] = dict(edges=len(Rt), types=types)
    log(f"    vertex orbits closed under NS-adjacency: {okBp}  [{time.time() - t0:.0f}s]")
    res["Bp_ok"] = okBp
    # ---------------------------------------------------------------- (C) violations
    reps, S = load_reps(sc)
    funcs = []
    for j, s in enumerate(reps):
        dn, w = functional_from_slack(sc, s)
        funcs.append((dn, np.array(w, dtype=np.int64)))
    res["C"] = {}
    okC = True
    for k in range(2, d + 1):
        o, den = orbs[f"PR_{k}"]
        Xs = np.array([coords_int(sc, P) for P in o], dtype=np.int64)        # den * X
        best = None
        for j in range(len(reps)):
            if j == 25:
                continue
            dn, w = funcs[j]
            # den*dn*slack = den*h0 - h.(den X)
            v = den * w[0] - Xs @ w[1:]
            i = int(np.argmin(v))
            val = Fraction(int(v[i]), den * dn)
            if best is None or val < best[0]:
                best = (val, j, i)
        val, j, i = best
        # exact re-evaluation with Fractions on the behaviour
        P = o[i]
        Xf = [Fraction(int(c), den) for c in coords_int(sc, P)]
        dn, w = funcs[j]
        sl = (Fraction(int(w[0])) - sum(int(w[1 + t]) * Xf[t] for t in range(sc.dim))) / dn
        assert sl == val
        okC &= val < 0
        log(f"(C) PR_{k}: most negative listed slack over the PR_{k} orbit = {val} (class {j}, orbit element {i}): "
            f"violated: {val < 0}")
        res["C"][f"PR_{k}"] = dict(min_slack=str(val), cls=j)
    allok = okB and okBp and okC
    log("HYPOTHESIS (ii) VERIFIED INDEPENDENTLY" if allok else "CHECK FAILED")
    log(f"[total {time.time() - T0:.0f}s]")
    json.dump(res, open("logs/IND_ns.json", "w"), default=str, indent=1)


if __name__ == "__main__":
    main()
