"""
kd_check_orbits.py -- independent check (separate code) that the facets of K_d found by the naive DD of kd_check.py
are exactly the union of the orbits of the listed class representatives under PHYSICAL relabellings, and that the
first class is a relabelled CGLMP_d inequality.

Representation (different from kd_facets.py): a facet is its integer slack function on the d^4 deterministic points
lam = (a0, a1, b0, b1), s(lam) = c0 - sum_i c_i(n_i(lam)), n = (b0-a0, a0-b1, a1-b0, b1-a1) mod d, made primitive.
The group is generated by explicit relabellings of lam: outcome shift of one measurement, multiplication of all
outcomes by a unit, swap a0<->a1, swap b0<->b1, party swap (a0,a1) <-> (b0,b1).  Orbits by breadth-first search.
"""
import sys
import json
import math
import itertools
import numpy as np
from kd_check import naive_facets, kd_points


def lam_list(d):
    return list(itertools.product(range(d), repeat=4))


def slack_of_table(c, c0, d, lams):
    out = []
    for (a0, a1, b0, b1) in lams:
        n = ((b0 - a0) % d, (a0 - b1) % d, (a1 - b0) % d, (b1 - a1) % d)
        out.append(c0 - sum(c[i][n[i]] for i in range(4)))
    g = 0
    for v in out:
        g = math.gcd(g, abs(v))
    return tuple(v // g for v in out)


def slack_of_ray(r, d, lams):
    """ray (h0, h) of the naive DD: h0 + h.v >= 0 on K_d vertices v (one-hot, outcome 0 dropped)"""
    h0 = r[0]; h = r[1:]
    out = []
    for (a0, a1, b0, b1) in lams:
        n = ((b0 - a0) % d, (a0 - b1) % d, (a1 - b0) % d, (b1 - a1) % d)
        v = h0 + sum(h[i * (d - 1) + n[i] - 1] for i in range(4) if n[i] > 0)
        out.append(v)
    g = 0
    for v in out:
        g = math.gcd(g, abs(v))
    return tuple(v // g for v in out)


def generators(d):
    units = [u for u in range(2, d) if math.gcd(u, d) == 1]
    gens = []
    for k in range(4):                                   # shift one measurement's outcomes
        gens.append(lambda l, k=k: tuple((l[i] + (1 if i == k else 0)) % d for i in range(4)))
    for u in units:
        gens.append(lambda l, u=u: tuple((u * x) % d for x in l))
    gens.append(lambda l: (l[1], l[0], l[2], l[3]))      # a0 <-> a1
    gens.append(lambda l: (l[0], l[1], l[3], l[2]))      # b0 <-> b1
    gens.append(lambda l: (l[2], l[3], l[0], l[1]))      # party swap
    return gens


def orbit(s, d, lams, idx, gens):
    seen = {s}
    frontier = [s]
    perms = []
    for g in gens:
        perms.append([idx[g(l)] for l in lams])        # lam -> g(lam)
    while frontier:
        new = []
        for t in frontier:
            for p in perms:
                # (t o g^{-1})(g lam) = t(lam): new slack at position p[i] is t[i]
                u = [0] * len(t)
                for i, j in enumerate(p):
                    u[j] = t[i]
                u = tuple(u)
                if u not in seen:
                    seen.add(u); new.append(u)
        frontier = new
    return seen


if __name__ == "__main__":
    d = int(sys.argv[1])
    lams = lam_list(d)
    idx = {l: i for i, l in enumerate(lams)}
    gens = generators(d)
    facets = {slack_of_ray(r, d, lams) for r in naive_facets(kd_points(d))}
    classes = json.load(open(f"kd_facets_d{d}.json"))
    union = set()
    for ci, cl in enumerate(classes):
        s = slack_of_table(cl["c"], cl["c0"], d, lams)
        O = orbit(s, d, lams, idx, gens)
        union |= O
        print(f"class {ci}: orbit size {len(O)} (listed {cl['size']}), all in naive DD list: {O <= facets}")
    print(f"union of orbits == naive DD facet set: {union == facets}  ({len(union)} / {len(facets)})")
    # CGLMP identification of class 0
    c = classes[0]["c"]
    ok = True
    for (a0, a1, b0, b1) in lams:
        n = ((b0 - a0) % d, (a0 - b1) % d, (a1 - b0) % d, (b1 - a1) % d)
        F = sum(c[i][n[i]] for i in range(4))
        Pi = (a0 - b0) % d + (b1 - a0) % d + (b0 - a1) % d + (a1 - b1 - 1) % d
        ok &= (F == -(Pi - (d - 1)))
    print(f"class 0 functional == (d-1) - Pi_CGLMP on all {d**4} deterministic points: {ok}")
